/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hmm.h"


void
add_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;
	
#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int x;
	scanf("%d",&x);
	int t;
	add_1_arg.a[0]=x;
	for(int i = 1; i <=x;i++) {
		scanf("%d", &t);
		add_1_arg.a[i] = t;
	}
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Result:%d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
grt_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  grt_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GRT_PROG, GRT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int t;
	for(int i = 0; i <3;i++) {
		scanf("%d", &t);
		grt_1_arg.a[i] = t;
	}
	result_1 = grt_1(&grt_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Result:%d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
sine_prog_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	numbers  sine_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SINE_PROG, SINE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int t;
	scanf("%d",&t);
	sine_1_arg.a[0] = t;
	result_1 = sine_1(&sine_1_arg, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Result:%f\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
fact_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  fact_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FACT_PROG, FACT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int t;
	scanf("%d",&t);
	fact_1_arg.a[0] = t;
	result_1 = fact_1(&fact_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Result:%d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
rev_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  rev_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, REV_PROG, REV_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int t;
	scanf("%d",&t);
	rev_1_arg.a[0] = t;
	result_1 = rev_1(&rev_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Result:%d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
sumd_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  sumd_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUMD_PROG, SUMD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int t;
	scanf("%d",&t);
	sumd_1_arg.a[0] = t;
	result_1 = sumd_1(&sumd_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Result:%d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	switch(atoi(argv[2])) {
		
		case 1:
			add_prog_1 (host);
			break;
		
		case 2:
			grt_prog_1 (host);
			break;
		
		case 3:
			sine_prog_1 (host);
			break;
		
		case 4:
			fact_prog_1 (host);
			break;
		
		case 5:
			rev_prog_1 (host);
			break;
		
		case 6:
			sumd_prog_1 (host);
			break;
		default:
			printf("invalid input");
			
	}

exit (0);
}
