/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hmm.h"
#include <math.h>
#define max(a,b) a>b ? a:b
int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	for(int i=1; i <=(argp->a)[0];i++){
		result += (argp->a)[i];
	
	}

	return &result;
}

int *
grt_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;
	
	printf("grt(%d,%d,%d) is called\n",(argp->a)[0],(argp->a)[1],(argp->a)[2]);
        result = max((argp->a)[0],(argp->a)[2]);
        result = max((argp->a)[1],result);

	return &result;
}

double *
sine_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static double  result;

	result = sin((argp->a)[0]);

	return &result;
}

int *
fact_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	int temp = (argp->a)[0];
	int factRet = 1;
	for(int i = 1; i < temp + 1; i++){
		factRet *= i;
	}
	result = factRet;
	printf("%d",factRet);
	return &result;
}

int *
rev_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result = 0;

	int temp;
	
	while((argp->a)[0]>0) {
		result *= 10;
		temp = (argp->a)[0]%10;
		(argp->a)[0] /= 10;
		result += temp;
		
	}

	return &result;
}

int *
sumd_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;
 
	int temp;
	
	while((argp->a)[0]>0) {
		temp = (argp->a)[0]%10;
		(argp->a)[0] /= 10;
		result += temp;
	}

	return &result;
}
